import React from 'react'

export const Body = () => {
    return (
        <div>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
            <h3> Body </h3>
        </div>
    )
}

export default Body